

export default {

    //################## RESULTS ENCODING (DAPP->DESMO-HUB)
    POS_INTEGER:0,
    POS_FLOAT:1,
    NEG_INTEGER:2,
    NEG_FLOAT:3,
    STRING:4,
    BOOLEAN:5,
    NO_CONSENSUS:6,
    FUTURE_USE_3:7,

    INTERNAL_TEST_REQUEST_ID:"INTERNAL_TEST_REQUEST_ID",
    INTERNAL_TEST_REQUEST_ID_ZION:"INTERNAL_TEST_REQUEST_ID_ZION",
    INTERNAL_TEST_REQUEST_ID_REJECT_1:"INTERNAL_TEST_REQUEST_ID_REJECT_1",
    INTERNAL_TEST_REQUEST_ID_REJECT_2:"INTERNAL_TEST_REQUEST_ID_REJECT_2",
    INTERNAL_TEST_REQUEST_ID_REJECT_3:"INTERNAL_TEST_REQUEST_ID_REJECT_3"
   

    
}