const axios = require('axios');

/*
Registered USER (the same in all 4 zions)
{
    "email":"desmold@vaimee.com",
    "password":"desmo"
}
*/
const config = {

    zions: [
        { url: "https://desmold-zion-1.vaimee.it/", token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY1OTYxMDU4MiwiZXhwIjoxNjYwMjE1MzgyfQ.7xA8zW_wvQOWnXL7xMZDHbaqCdsLt8b_myu7hA1_WWA",tds:[
            "servient",
            "temp_01",
            "temp_02",
            "stopligth_01",

            "000048b02d15bdcd",
            "000048b02d15c31f"
        ] },
        { url: "https://desmold-zion-2.vaimee.it/", token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY1OTYxMDYxNCwiZXhwIjoxNjYwMjE1NDE0fQ.MuSW7LzGkCE9qMNTXnAl19-l0lI7HL1twjcX3QYF-4E" , tds: [
            "temp_02",
            "temp_03",
            "stopligth_02",

            "000048b02d15bc87",
            "000048b02d15bc3d",
            "000048b02d15bc7c"
        ]},
        { url: "https://desmold-zion-3.vaimee.it/", token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY1OTYxMDYyNywiZXhwIjoxNjYwMjE1NDI3fQ.HCmecgGpSrekb5-wtbDon5e8vlhs_IabCw2IUY0ZY-k" , tds: [
            "servient",
            "temp_03",
            "stopligth_03",

            "000048b02d15c319",
            "000048b02d15bc77",
            "000048b02d05a1c6"

        ]},
        { url: "https://desmold-zion-4.vaimee.it/", token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY1OTYxMDYzOSwiZXhwIjoxNjYwMjE1NDM5fQ.rstR_sT3IdfrsXCcpG6NqcebApBmXiZilJowAKIE9BI" , tds: [
            "temp_03",

            "000048b02d15c319_2",
            "000048b02d15bda5"
        ]},
    ],
    wam: "https://desmold-sensors.vaimee.it/"

}



async function getTD(url) {
    console.log("getTD: "+url);
    return (await axios.get(url)).data;
}


async function registerTDTo(directory,jsonTD,auth=null, forceCreate = false) {
    var headers = { 'Content-Type': 'application/ld+json' };
    if (auth !== null) {
        headers = { 'Content-Type': 'application/ld+json', 'Authorization': 'Bearer ' + auth.replaceAll("\n", '').replaceAll("\r", '').trim() };
        // console.log("You are using Authorization: ", headers);
    }
    if (forceCreate || jsonTD.id === undefined) {
        /*
        With "forceCreate" if the jsonTD has an ID it will be removed
        and then the TD will has a new ID generated by the Directory
        */
        const jsonTD_withNoID = jsonTD;
        delete jsonTD_withNoID.id;
        return (await axios.post(
            directory + "things",
            jsonTD_withNoID,
            { headers: headers }
        )).status === 200

    } else {
        /*
        Use the WAM ID and so we need to PUT the TD
        and not to create it (POST)
        */
        const id = jsonTD.id;
        return (await axios.put(
            directory + "things/" + id,
            jsonTD,
            { headers: headers }
        )).status === 200
    }
}

async function registerALL(){
    var _tot=0;
    var _err = 0;
    var _ok = 0;
    var _fail = 0;
   for(var z of config.zions){
        for(var td of z.tds){
            console.log("Registering "+td+ " on "+ z.url);
            _tot++;
            try{
                const jsonTD= await getTD(config.wam+td);
                if(jsonTD===undefined){
                    _err++;
                    console.log("Err: TD undefined!");
                }else{
                    
                    if((await registerTDTo(z.url,jsonTD,z.token))){
                        _ok++;
                    }else{
                        _fail++;
                    }
                }
            }catch(err){
                _err++;
                console.log("Err: ",err);
            }
        }
   }
   console.log("RESULTS:");
   console.log("TOTs",_tot);
   console.log("ERRs",_err);
   console.log("FAILs",_fail);
   console.log("OKs",_ok);
}

registerALL();